// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;
public class IndexTest {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @Before
  public void setUp() {
    driver = new FirefoxDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void index() {
    // Test name: index
    // Step # | name | target | value | comment
    // 1 | open | http://127.0.0.1:8080/ |  | 
    driver.get("http://127.0.0.1:8080/");
    // 2 | setWindowSize | 550x692 |  | 
    driver.manage().window().setSize(new Dimension(550, 692));
    // 3 | click | linkText=do external links work? |  | 
    driver.findElement(By.linkText("do external links work?")).click();
    // 4 | click | linkText=do simple relative internal links work? |  | 
    driver.findElement(By.linkText("do simple relative internal links work?")).click();
    // 5 | click | linkText=do general relative links work |  | 
    driver.findElement(By.linkText("do general relative links work")).click();
    // 6 | click | linkText=do simple absolute links work |  | 
    driver.findElement(By.linkText("do simple absolute links work")).click();
    // 7 | click | linkText=do general absolute links work |  | 
    driver.findElement(By.linkText("do general absolute links work")).click();
    // 8 | click | linkText=do URLs with spaces work |  | 
    driver.findElement(By.linkText("do URLs with spaces work")).click();
    // 9 | click | linkText=do URLs with %20 work |  | 
    driver.findElement(By.linkText("do URLs with %20 work")).click();
    // 10 | click | linkText=do TXT files work |  | 
    driver.findElement(By.linkText("do TXT files work")).click();
    // 11 | click | css=tr:nth-child(1) img |  | 
    driver.findElement(By.cssSelector("tr:nth-child(1) img")).click();
    // 12 | click | css=tr:nth-child(2) img |  | 
    driver.findElement(By.cssSelector("tr:nth-child(2) img")).click();
    // 13 | click | css=html |  | 
    driver.findElement(By.cssSelector("html")).click();
    // 14 | close |  |  | 
    driver.close();
  }
}
